### ISSUE TITLE
todoFRP throwing errors

### ISSUE THREAD

**Issue by ethagnawl** [hoplon/demos#11]
I'm seeing the following when trying to view the [demo](https://tailrecursion.github.io/hoplon-demos/todoFRP/) in latest Chrome and Firefox:

Uncaught Error: No protocol method IDeref.-deref defined for type undefined: 
Uncaught ReferenceError: tailrecursion is not defined

**Comment by SanAngeloMike** [comment]
I am also unable to view todoFRP in latest Chrome or Firefox. todoFRP-HTML works fine.

**Comment by SanAngeloMike** [comment]
>> I am also unable to view todoFRP in latest Chrome or Firefox. todoFRP-HTML works fine.

Update: It works fine when cloned to my desktop, just not from the link on Github. No worries.

**Comment by mynomoto** [comment]
I'm closing this, please reopen if still relevant.
