### ISSUE TITLE
hoplon.svg does not support dom class

### ISSUE THREAD

**Issue by LauraSempere** [hoplon/demos#16]
According to [demo example](https://github.com/hoplon/demos/blob/master/plotSVG/src/chart.cljs.hl), if we pass a class to create a svg dom element, the class is not applied to the generated dom.

e.g. 

```
(c/container
        :id "some-id"
        :class "some-class")
```

The result code is 

```
<svg:svg id="some-id">...</svg:svg>
```

**Comment by mynomoto** [comment]
Hi, sorry about the delay responding this. You should use `:svg/class` instead of `:class` to get this working. I'm closing this, but feel free to reopen if the solution does not work.

Reference:
- https://github.com/hoplon/hoplon/wiki/Hoplon-with-SVG
