### ISSUE TITLE
jquery-date-picker demo depends

### ISSUE THREAD

**Issue by robjens** [hoplon/demos#26]
I am getting `clojure.lang.ExceptionInfo: Could not find artifact hoplon:twitter-bootstrap:jar:0.2.0-SNAPSHOT in clojars (https://clojars.org/repo/)` on the jquery datepicker demo.

Coincidentally, I am getting the same error on the latest `[hoplon/jquery-daterange-picker "0.0.8-0"]`. Are these just not published yet, am I missing a repository or something else I should/could do to get this running? The (older) versions keep giving me JS replace method errors so I figured I would try the demo / update dependencies and I run into the problem of them not being available in Clojars.

Cheers...

**Comment by flyboarder** [comment]
@robjens Highest version pushed to clojars is `0.0.5-0`

**Comment by robjens** [comment]
@flyboarder Right... I wasn't too sure if I had the right repo since there is quite the large gap between dev/github (current) 0.0.8 and the latest remote but I guess the subsequent 0.0.6 and 0.0.7 weren't deemed stable enough then or author just didn't have time to push it.

I recon the twitter-bootstrap dependency might be adjusted to include the non-SNAPSHOT 0.2.0 release for the demo `build.boot` file then, as this is the latest published. Anyway, I can do that myself of course just figured I would point them out since ... well this kinda gets in the way of a flawless first try of any new users.

Could do a pull request if needed, just thought I'd check here first...

**Comment by flyboarder** [comment]
PR's are welcome, im sure someone with write access will pull in the changes. You can always bug them on slack if it's urgent.

**Comment by robjens** [comment]
Don't think so but thanks for the info
